### ISSUE TITLE
email based authentication

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/spiderlib#4]
- there is already code, be careful
- use https://modules.vlang.io/net.smtp.html
- use e.g. https://app.brevo.com/settings/keys/smtp is free secure smtp service
- use htmx
- use e.g. login form from https://flowbite.com/docs/components/forms/
- remember login state in browser datsstor, so next time we come back we don't have to do every time the check on email

**Comment by timurgordon** [comment]
completed with b337858, examples can be found in spiderlib/auth/examples. Done using brevo so please reach out to run examples to get the SMTP credentials, or create your own credentials. Moving remembering login state to separate issue since that is beyond email auth and also concerns tfconnect/basic_auth
